### ISSUE TITLE
mod_unique_id cause Apache to fail restart on first coverge

### ISSUE THREAD

**Issue by niven01** [svanzoest-cookbooks/apache2#259]
Hello,

I've encountered a problem after introducing unique_id where Apache fails to restart.
The work around at this moment is a `killall httpd` and re run chef-client

This can be reproduced in test-kitchen by just including two recipes:  

-
    name: upstream_apache
    run_list:
      - "recipe[apache2]"
      - "recipe[apache2::mod_unique_id]"

The behavior seen is that httpd is stopped but only the master process is killed. There are a bunch of httpd orphans still sitting there listening on 80 and 443

When Apache tries to start it fails as ports are already in use.

Every now and then it will succeed which suggests to me this maybe a timing issue and that httpd start is happening before the stop has completed. 

Error:

```      ================================================================================
           Error executing action `restart` on resource 'service[apache2]'
           
       ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service httpd restart ----
           STDOUT: Stopping httpd: [  OK  ]
           Starting httpd: [FAILED]
           STDERR: [Thu Oct 09 11:56:26 2014] [warn] NameVirtualHost *:80 has no VirtualHosts
           (98)Address already in use: make_sock: could not bind to address [::]:80
           (98)Address already in use: make_sock: could not bind to address 0.0.0.0:80
           
       no listening sockets available, shutting down
           Unable to open logs
           ---- End output of /sbin/service httpd restart ----
           Ran /sbin/service httpd restart returned 1
           
           
       Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb
           
            24: service 'apache2' do
            25:   service_name node['apache']['package']
            26:   case node['platform_family']
            27:   when 'rhel'
            28:     reload_command '/sbin/service httpd graceful'
            29:   when 'debian'
            30:     provider Chef::Provider::Service::Debian
            31:   when 'arch'
            32:     service_name 'httpd'
            33:   end
            34:   supports [:start, :restart, :reload, :status]
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:24:in `from_file'
           
           service("apache2") do
           
         action [:enable, :start]
             updated true
             supports {:restart=>true, :reload=>true, :status=>true, :start=>true}
             retries 0
             retry_delay 2
             guard_interpreter :default
             service_name "httpd"
             enabled true
             running true
             pattern "apache2"
             reload_command "/sbin/service httpd graceful"
             cookbook_name "apache2"
             recipe_name "default"
             only_if "/usr/sbin/httpd -t"
           end
```

**Comment by svanzoest** [comment]
This seems to be an issue with the 2.2 init scripts. We did remove a `&& sleep 1` from service resource in the cookbook (https://github.com/svanzoest-cookbooks/apache2/commit/f0fc1ce490a5fccb10915c1e5088a4caaa352db5)  seems like this showed up when we removed it?

We clearly do not need it on the newer platforms, but it seems like `mod_security` and `mod_unique_id` cause things to take longer in a way that the init scripts do not handle gracefully. When tried to look back to see what was the reasoning for the sleeps to get added, but there was nothing in the commits that indicated a reason. I guess we found two. ;-)

**Comment by drpebcak** [comment]
I believe this should fix it - it seems like this is only being experienced on rhel systems.

**Comment by gitgc** [comment]
I'm still seeing this exact issue on Apache 2.2/Centos 6.5, using the latest 3.1.0 version of this cookbook. As described in original post, the parent apache process is killed, but a bunch of zombie apache processes are still running, binding the ports, preventing a restart without a killall httpd.

**Comment by drpebcak** [comment]
@gitgc what happens when you run `service httpd restart` manually on that box? Does it take a really long time or cause some sort of error?

**Comment by kalebwalton** [comment]
I am having this issue using latest version of this cookbook as well. When I adjust the restart/reload lines to be as follows, all is well:

    service 'apache2' do
      service_name node['apache']['service_name']
      case node['platform_family']
      when 'rhel'
        restart_command '/sbin/service httpd restart && sleep 1'
        reload_command '/sbin/service httpd graceful && sleep 1'
      when 'debian'
        provider Chef::Provider::Service::Debian
      when 'arch'
        service_name 'httpd'
      end
      supports [:start, :restart, :reload, :status]
      action [:enable, :start]
      only_if "#{node['apache']['binary']} -t", :environment => {           'APACHE_LOG_DIR' => node['apache']['log_dir'] }, :timeout => 10
    end

**Comment by niven01** [comment]
Just like to add this is still happening with 3.1.0 version of this cookbook for me
